version: '3.7'

services:

  iris:
    init: true
    hostname: iris
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris
    ports:
    - "52773:52773"
    - "1972:1972"
    volumes:
    - .:/app

  jupyter:
    container_name: jupyter
    build:
      context: jupyter
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_INSECURE_WRITES=true
    volumes: 
      - ./jupyter/notebooks:/home/jovyan/
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

