services:

  # InterSystems IRIS for Health
  iris:
    init: true
    hostname: iris
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irish
    ports:
    - "52773:52773"
    - "1972:1972"
    volumes:
    - .:/app
    #- ./irisdata:/irisdata
    #environment:
    #- ISC_DATA_DIRECTORY=/irisdata

  # Sample external database to integrate from InterSystems IRIS interoperability framework  
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: mysqlh
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"

  # Jupyter is used to access to FHIR projected data as relational tables and analyze data
  jupyter:
    container_name: jupyterh
    build:
      context: jupyter
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_INSECURE_WRITES=true
    volumes: 
      - ./jupyter/notebooks:/home/jovyan/
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

  kafka:
    image: apache/kafka:4.1.0-rc2
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/server.properties:/opt/kafka/config/server.properties
    environment:
      CLUSTER_ID: my-cluster-id
    entrypoint: >
      sh -c "
        if [ ! -f /tmp/kraft-combined-logs/meta.properties ]; then
          /opt/kafka/bin/kafka-storage.sh format -t $$CLUSTER_ID -c /opt/kafka/config/server.properties
        fi &&
        /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
        "