Class Demo.EventBridge.HIS.WSC.Msg.SubmitReportResponse Extends Ens.Response [ ProcedureBlock ]
{

Property SubmitReportResult As %String;

Storage Default
{
<Data name="SubmitReportResponseDefaultData">
<Subscript>"SubmitReportResponse"</Subscript>
<Value name="1">
<Value>SubmitReportResult</Value>
</Value>
</Data>
<DefaultData>SubmitReportResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
